server:
  port: 8002
spring:
  application:
    name: service-aliyun
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  oss:
    end-point: oss-cn-shenzhen.aliyuncs.com
    key-id: LTAI5tJofv2fwVBJiQ9T3Hit
    key-secret: xJ7VhSjMHU6S1Muhvb7AuQe7AJgG08
    bucket-name: atcwl-test
