server:
  port: 8008
spring:
  profiles:
    active: dev
  application:
    name: service-statistics
  datasource:
    url: jdbc:mysql://localhost:3306/guli_statistics?serverTimezone=GMT%2B8
    username: root
    password: BF2042CWLccc2020!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
test:
  a: my